# This is a basic workflow to help you get started with Actions
# author: Omar.Zapata@cern.ch 2020

name: SWAN CI/CD pipeline
on: 
  workflow_dispatch:
    inputs:
      package:
        description: 'Package Name'     
        required: true
        default: ''    
      version:
        description: 'Package Version'     
        required: true
        default: ''       
jobs:
  update-package:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master

    - name: Update package version
      run: |
        echo "Updating information for package = ${{ github.event.inputs.package }} version = ${{ github.event.inputs.version }}"

        PKG_NAME_LOWER=$(echo " ${{ github.event.inputs.package }}" | tr '[:upper:]' '[:lower:]')
        PKG_VER=$(echo ${{ github.event.inputs.version }} | sed -e 'e/v//g')
        sed -i "s/$(grep "$PKG_NAME_LOWER==" Dockerfile |  sed -e 's/\\//g')/            $PKG_NAME_LOWER==$PKG_VER /g" Dockerfile

    - name: Push
      uses: github-actions-x/commit@v2.7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: master
        name: "SWAN CI/CD pipeline"
        commit-message: "Updated package ${{ github.event.inputs.package }} to version ${{ github.event.inputs.version }}"
        rebase: 'true'
