
name: SWAN CI/CD pipeline
on: 
  workflow_dispatch:
    inputs:
      package_version:
        description: 'Package Version'     
        required: true
        default: ''       
      package_name:
        description: 'Package Name'     
        required: true
        default: ''       
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Printing input from the other repo"
        echo "Tags: pkg_ver = ${{ github.event.inputs.package_version }}  pkg_name = ${{ github.event.inputs.package_name }}" 
