# This is a basic workflow to help you get started with Actions

name: SWAN CI/CD pipeline
on: 
  workflow_dispatch:
    inputs:
      package:
        description: 'Package Name'     
        required: true
        default: ''    
      version:
        description: 'Package Version'     
        required: true
        default: ''       
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Printing input from the other repo"
        echo "Tags: pkg_ver = ${{ github.event.inputs.version }}  pkg_name = ${{ github.event.inputs.package }}"
